#!/usr/bin/env python
import sys

def main():
    original = read()
    result = translate(original)
    write(result)

def read():
    return [line.strip() for line in sys.stdin]

def translate(lines):
    return lines

def write(lines):
    print('\n'.join(lines))

if __name__ == '__main__':
    main()
